# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quaduser',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='quaduser',
            name='y_axis',
        ),
        migrations.RemoveField(
            model_name='quaduser',
            name='z_axis',
        ),
        migrations.AddField(
            model_name='quaduser',
            name='acc_x',
            field=models.PositiveIntegerField(default=0, verbose_name='acc_x'),
        ),
        migrations.AddField(
            model_name='quaduser',
            name='acc_y',
            field=models.PositiveIntegerField(default=0, verbose_name='acc_y'),
        ),
        migrations.AddField(
            model_name='quaduser',
            name='acc_z',
            field=models.PositiveIntegerField(default=0, verbose_name='acc_z'),
        ),
        migrations.AddField(
            model_name='quaduser',
            name='pitch',
            field=models.PositiveIntegerField(default=0, verbose_name='pitch'),
        ),
        migrations.AddField(
            model_name='quaduser',
            name='roll',
            field=models.PositiveIntegerField(default=0, verbose_name='roll'),
        ),
        migrations.AddField(
            model_name='quaduser',
            name='temp',
            field=models.PositiveIntegerField(default=0, verbose_name='temp'),
        ),
        migrations.AddField(
            model_name='quaduser',
            name='yaw',
            field=models.PositiveIntegerField(default=0, verbose_name='yaw'),
        ),
    ]
