# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170310_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quaduser',
            name='temp',
        ),
    ]
