# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_quaduser_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quaduser',
            name='thrust',
            field=models.PositiveIntegerField(default=0, verbose_name='thrust'),
        ),
    ]
